### ISSUE TITLE
Architecture Detection Aliases 

### ISSUE THREAD

**Issue by princespaghetti** [warrensbox/hubapp#23]
While attempting to use hubapp, it does not match on an alternate naming pattern although the binaries can be installed. I experience this on a linux/amd64 client with projects like goreleaser and other projects that leverage it https://github.com/goreleaser/goreleaser/releases/tag/v0.140.0 In the link the tar.gz is identified by "x86_64" rather than "amd64" which is returned by runtime.goos in the install file. https://github.com/open-policy-agent/conftest/releases/tag/v0.20.0 is another example. Happy to contribute a fix, but wanted to check if you had a specific way you wanted to approach this.

**Comment by warrensbox** [comment]
I'm sorry I missed this. You can go ahead and open a pull request.
